##
## EPITECH PROJECT, 2024
## HEADER
## File description:
## HEADER
##

SRC	=	./src/zappy_ai

NAME =	zappy_ai

$(NAME)	:
			cp $(SRC) ./

all: $(NAME)

clean:
		rm -rf zappy_ai

fclean:	clean

re:	fclean all

.PHONY: all clean fclean re
