name : Zappy Unit tests

on:
  push:
    branches:
      - main
      - dev
      - dev-ia

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install pytest
      run: pip install pytest pytest-cov pytest-mock
    - name: Make unit tests
      run: make tests_run
